name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 src tests --max-line-length=88 --extend-ignore=E203,W503

    - name: Format check with black
      run: |
        black --check --diff src tests

    - name: Import sort check with isort
      run: |
        isort --check-only --diff src tests

  docker:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: nb_streamer:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        # Start container
        docker run --rm -d -p 8080:8000 --name test_container nb_streamer:latest
        sleep 10
        
        # Health check with retries
        for i in {1..5}; do
          if curl -f http://localhost:8080/health; then
            echo "Health check passed on attempt $i"
            docker stop test_container
            exit 0
          fi
          echo "Health check attempt $i failed, retrying in 5 seconds..."
          sleep 5  
        done
        
        # If we get here, all health checks failed
        echo "Health check failed after 5 attempts"
        echo "Container logs:"
        docker logs test_container
        docker stop test_container
        exit 1
